# Generated by Django 4.1.7 on 2023-03-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='name',
            new_name='nome',
        ),
    ]
