# Generated by Django 4.1.7 on 2023-03-24 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='name',
            new_name='nome',
        ),
    ]
